### ISSUE TITLE
minimum payout setting only works after multiple tries 

### ISSUE THREAD

**Issue by mihalycsaba** [scala-network/scala-pool#12]
I have 3 miners with 3 different ip addresses(cloud, home, mobile) tried multiple times with every address to set the minimum payout amount, managed to change it only once to 500 with my home ip.

**Comment by mihalycsaba** [comment]
oh and I'm using the official pool

**Comment by mihalycsaba** [comment]
okay, tried it again 2 hours later with my home ip and manged to set it to 5000, but it still feels like this is a bug. It kept telling me before that it didn't see my ip mining.

**Comment by ahmyi** [comment]
Will look into this issue. It could be due to ipv6.

**Comment by mihalycsaba** [comment]
> Will look into this issue. It could be due to ipv6.

I have only ipv4 addresses
