### ISSUE TITLE
Worker Statistics: Connection Error

### ISSUE THREAD

**Issue by sm18038589** [scala-network/scala-pool#13]
I have been getting a "connection error" when I try to load "My Stats and Payment History" using my Scala address. It's been happening for a while now. Screenshot below. Please advise/resolve. Thank you!

![image](https://user-images.githubusercontent.com/88849684/154085593-a31f97f2-d27f-4496-a30e-12dce4f3c620.png)

**Comment by ahmyi** [comment]
Can you check if error persists?
