### ISSUE TITLE
HELP (Hello, I've been struggling with this pool all day)

### ISSUE THREAD

**Issue by Dev1124** [scala-network/scala-pool#14]
Hello, I've been struggling with this pool all day
https://github.com/scala-network/scala-pool/blob/master/docs/usages.md

tried different versions of machines, everywhere the same error

![2022-11-08_23-29-17](https://user-images.githubusercontent.com/117777060/200672258-0237730f-0553-4b51-84e0-1bbef0c5c198.png)

**Comment by Dev1124** [comment]
root@vdska:~/pool# node init.js
internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);

**Comment by aleksander-haugas** [comment]
Why you running In root?

**Comment by Dev1124** [comment]
"Why you running In root?"
Do you think it's because of this?

The fact is that the instructions indicate to create a new user without ssh access, and I put the pool on VDS, I can't work without ssh

now I'll just try to create a new user and do everything from under him

**Comment by Dev1124** [comment]
pool@vdska:~/pool$ node init.js
internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/pool/pool/node_modules/dateformat/lib/dateformat.js
require() of ES modules is not supported.
require() of /home/pool/pool/node_modules/dateformat/lib/dateformat.js from /home/pool/pool/lib/core/logger.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename dateformat.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/pool/pool/node_modules/dateformat/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/pool/pool/lib/core/logger.js:24:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_REQUIRE_ESM'
}
pool@vdska:~/pool$

**Comment by aleksander-haugas** [comment]
In the docs indicates you to use (node init.js -config=config_backup.json) I think you also need have configured you config.json

**Comment by Dev1124** [comment]
In the docs indicates you to use (node init.js -config=config_backup.json) I think you also need have configured you config.json

I set everything up, all ports and services work, but the pool does not start and still the same error
+ I am attaching my config file

![2022-11-10_00-04-20](https://user-images.githubusercontent.com/117777060/200941909-d6d3390d-08e5-4f5c-bfc5-56e6611d86bf.png)

-------------------------------------------------------

[config.txt](https://github.com/scala-network/scala-pool/files/9975128/config.txt)

**Here are the main parameters**

```
"daemon": {
        "host": "127.0.0.1",
        "port": 11812
    }
    "wallet": {
        "host": "127.0.0.1",
        "port": 20189
    }
    "redis": {
        "host": "127.0.0.1",
        "port": 6379,
        "auth": null,
		"db":5
    }
```

**Comment by Dev1124** [comment]
ohhh
The point was that some modules were too new versions.
