### ISSUE TITLE
Help new problem - hostname: 'api.ipgeolocationapi.com'

### ISSUE THREAD

**Issue by Dev1124** [scala-network/scala-pool#15]
now new problem when i connect with my miner it gives this

![2022-11-10_20-49-57](https://user-images.githubusercontent.com/117777060/201170360-eb9858c5-db91-4dd0-942a-df413662347a.png)
```

Error: getaddrinfo ENOTFOUND api.ipgeolocationapi.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api.ipgeolocationapi.com'
}

```

**Comment by ahmyi** [comment]
I have update isEnabled to false for now

**Comment by Dev1124** [comment]
I changed the domain to api.ipapi.com

**Comment by Dev1124** [comment]
https://happy-mine.online/index.html 
this is what comes out so far 
Pool started successfully
