### ISSUE TITLE
we have balls: NaN (unloked : NaN) UNABLE T TRANSFER : 375000

### ISSUE THREAD

**Issue by Dev1124** [scala-network/scala-pool#16]
we have balls: NaN (unloked : NaN) UNABLE T TRANSFER : 375000
There is an xla in the wallet

**Comment by Dev1124** [comment]
we have balance: NaN (unloked : NaN) UNABLE T TRANSFER : 375000

**Comment by ahmyi** [comment]
Its not connected to your wallet rpc
