### ISSUE TITLE
TOR support [NO NEED] [OLD]

### ISSUE THREAD

**Issue by GustavoSchip** [scala-network/scala-pool#18]
When u try to connect to this pool with tor enabled, it just straight up refuses to connect no questions asked.

I hope this could be changed as I want to anonymously mine XLA.

Thanks for the support 🫶

**Comment by aleksander-haugas** [comment]
have you checked your network firewall? iptables, ufw, pf...etc?

**Comment by GustavoSchip** [comment]
> have you checked your network firewall? iptables, ufw, pf...etc?

Yes, but this is a stupid old question/issue of mine.
I moved on to I2P and just use other protection method's for something like this and all the other services that don't natively support it.
