### ISSUE TITLE
Host error

### ISSUE THREAD

**Issue by krazymaez6** [scala-network/scala-pool#6]
Error 504
Ray ID: 6365009e7872ed7b •
2021-03-27 01:56:28 UTC
Gateway time-out.      Said it was issues at host project scarlet 1 sec

**Comment by krazymaez6** [comment]
doing more lookinto it finding this

**Comment by krazymaez6** [comment]
Uncaught TypeError: Cannot read property 'length' of null
    at n (Chart.min.js:11)
    at new t.Controller (Chart.min.js:11)
    at new t (Chart.min.js:12)
    at createCharts (eval at globalEval (jquery.min.js:2), <anonymous>:143:28)

**Comment by krazymaez6** [comment]
cdn cloudflare floder
thats all i could do donate me xla outa passion to try and help
SvmeZVRqEFN8C7cDcTN9sGJzn6PVeXbp6RZMFRNnBNqUSG1fs7Zo9WLbmiwZphG7M9TCvv1MxJm6N8C9hBPF2q2y1J4Sr1pUU this it's issues on links to hashcode on payment reference

**Comment by ahmyi** [comment]
May i know what the actual issue is?

**Comment by krazymaez6** [comment]
It is because the explorer.scalaproject wasn't working.

**Comment by ahmyi** [comment]
Ok can close issue as it is not related to pool

**Comment by krazymaez6** [comment]
Sorry I would have closed but I went to another job and my daughter broke my laptop at the same time!
