### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by Fedsd1** [scala-network/scala-pool#7]
3972 verbose stack Error: command failed
3972 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v15.12.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
3972 verbose stack     at ChildProcess.emit (node:events:369:20)
3972 verbose stack     at maybeClose (node:internal/child_process:1067:16)
3972 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
3973 verbose pkgid cryptoforknote-util@8.1.0
3974 verbose cwd /home/pool/pool
3975 verbose Linux 4.4.0-109-generic
3976 verbose argv "/root/.nvm/versions/node/v15.12.0/bin/node" "/root/.nvm/versions/node/v15.12.0/bin/npm" "install"
3977 verbose node v15.12.0
3978 verbose npm  v7.6.3
3979 error code 1
3980 error path /home/pool/pool/node_modules/cryptoforknote-util
3981 error command failed
3982 error command sh -c node-gyp rebuild
3983 error make: Entering directory '/home/pool/pool/node_modules/cryptoforknote-util/build'
3983 error   CXX(target) Release/obj.target/cryptoforknote/src/main.o
3983 error cryptoforknote.target.mk:136: recipe for target 'Release/obj.target/cryptoforknote/src/main.o' failed
3983 error make: Leaving directory '/home/pool/pool/node_modules/cryptoforknote-util/build'
3984 error gyp info it worked if it ends with ok
3984 error gyp info using node-gyp@7.1.2
3984 error gyp info using node@15.12.0 | linux | x64
3984 error gyp info find Python using Python version 3.5.2 found at "/usr/bin/python3"
3984 error gyp info spawn /usr/bin/python3
3984 error gyp info spawn args [
3984 error gyp info spawn args   '/root/.nvm/versions/node/v15.12.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
3984 error gyp info spawn args   'binding.gyp',
3984 error gyp info spawn args   '-f',
3984 error gyp info spawn args   'make',
3984 error gyp info spawn args   '-I',
3984 error gyp info spawn args   '/home/pool/pool/node_modules/cryptoforknote-util/build/config.gypi',
3984 error gyp info spawn args   '-I',
3984 error gyp info spawn args   '/root/.nvm/versions/node/v15.12.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
3984 error gyp info spawn args   '-I',
3984 error gyp info spawn args   '/root/.cache/node-gyp/15.12.0/include/node/common.gypi',
3984 error gyp info spawn args   '-Dlibrary=shared_library',
3984 error gyp info spawn args   '-Dvisibility=default',
3984 error gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/15.12.0',
3984 error gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v15.12.0/lib/node_modules/npm/node_modules/node-gyp',
3984 error gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/15.12.0/<(target_arch)/node.lib',
3984 error gyp info spawn args   '-Dmodule_root_dir=/home/pool/pool/node_modules/cryptoforknote-util',
3984 error gyp info spawn args   '-Dnode_engine=v8',
3984 error gyp info spawn args   '--depth=.',
3984 error gyp info spawn args   '--no-parallel',
3984 error gyp info spawn args   '--generator-output',
3984 error gyp info spawn args   'build',
3984 error gyp info spawn args   '-Goutput_dir=.'
3984 error gyp info spawn args ]
3984 error gyp info spawn make
3984 error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
3984 error g++: internal compiler error: Killed (program cc1plus)
3984 error Please submit a full bug report,
3984 error with preprocessed source if appropriate.
3984 error See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
3984 error make: *** [Release/obj.target/cryptoforknote/src/main.o] Error 4
3984 error gyp ERR! build error
3984 error gyp ERR! stack Error: `make` failed with exit code: 2
3984 error gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v15.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
3984 error gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
3984 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
3984 error gyp ERR! System Linux 4.4.0-109-generic
3984 error gyp ERR! command "/root/.nvm/versions/node/v15.12.0/bin/node" "/root/.nvm/versions/node/v15.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
3984 error gyp ERR! cwd /home/pool/pool/node_modules/cryptoforknote-util
3984 error gyp ERR! node -v v15.12.0
3984 error gyp ERR! node-gyp -v v7.1.2
3984 error gyp ERR! not ok
3985 verbose exit 1

**Comment by krazymaez6** [comment]
is this a mac. windows or android...? on my windows computer i had to mess with it unzip rezip and aprove the apps remotely

**Comment by ahmyi** [comment]
Try to use node v14 first and see if there is issue
